### PR TITLE
Convert forward slashes to backslashes on windows

### PR DESCRIPTION
**Pull request by retupmoca**
This fixes panda on windows.

### CODE REVIEW

**Comment by tadzik** [comment]
I have mixed feelings about this one, and it's been here for so long, because it feels weird to me that .relative is a almost a no-op here but converts slashes. Does .IO.path achieve the same result, could we use that instead? Again, sorry to keep it open for so long.

**Comment by lizmat** [comment]
> On 09 May 2015, at 16:59, Tadeusz Sośnierz <notifications@github.com> wrote:
> 
> I have mixed feelings about this one, and it's been here for so long, because it feels weird to me that .relative is a almost a no-op here but converts slashes. Does .IO.path achieve the same result, could we use that instead? Again, sorry to keep it open for so long.

Not sure how relevant, but one of the ideas of the newio branch is to only expose forward slashes at the P6 level.


Liz

**Comment by tadzik** [comment]
Okay, I've slacked off for full 4 months with this, and I figured it's time to accept it :) Here's a thing though: as a default, $exclude is False, so Bool. In tests it's an Array of Str, and here it's used as a single Str :) I will typify the API properly and pull this change in along with it.

**Comment by tadzik** [comment]
Ok, I decided to make it a user's responsibility after all. I fixed it in panda with https://github.com/tadzik/panda/commit/6cbf3f14583975edfec4cf3af807fc427d55f10b and also fixed File::Find's tests and documentation to underline and verify that: https://github.com/tadzik/File-Find/commit/522363b2ac2b50eba4435e3be3f79d5841faf365

Can you confirm that it fixes the issue for you and whether you agree with the change? :)

**Comment by retupmoca** [comment]
Works for me! Panda has been working on Windows again, which is mostly what I cared about.

**Comment by tadzik** [comment]
Okay, awesome :) Thanks!

**Pull request closed without merging**
